// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockTransferRepo creates a new instance of MockTransferRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransferRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransferRepo {
	mock := &MockTransferRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTransferRepo is an autogenerated mock type for the TransferRepo type
type MockTransferRepo struct {
	mock.Mock
}

type MockTransferRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransferRepo) EXPECT() *MockTransferRepo_Expecter {
	return &MockTransferRepo_Expecter{mock: &_m.Mock}
}

// CreateTransfer provides a mock function for the type MockTransferRepo
func (_mock *MockTransferRepo) CreateTransfer(ctx context.Context, fromUserId int32, toUserId int32, amount int32) error {
	ret := _mock.Called(ctx, fromUserId, toUserId, amount)

	if len(ret) == 0 {
		panic("no return value specified for CreateTransfer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32, int32, int32) error); ok {
		r0 = returnFunc(ctx, fromUserId, toUserId, amount)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTransferRepo_CreateTransfer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTransfer'
type MockTransferRepo_CreateTransfer_Call struct {
	*mock.Call
}

// CreateTransfer is a helper method to define mock.On call
//   - ctx context.Context
//   - fromUserId int32
//   - toUserId int32
//   - amount int32
func (_e *MockTransferRepo_Expecter) CreateTransfer(ctx any, fromUserId any, toUserId any, amount any) *MockTransferRepo_CreateTransfer_Call {
	return &MockTransferRepo_CreateTransfer_Call{Call: _e.mock.On("CreateTransfer", ctx, fromUserId, toUserId, amount)}
}

func (_c *MockTransferRepo_CreateTransfer_Call) Run(run func(ctx context.Context, fromUserId int32, toUserId int32, amount int32)) *MockTransferRepo_CreateTransfer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int32
		if args[1] != nil {
			arg1 = args[1].(int32)
		}
		var arg2 int32
		if args[2] != nil {
			arg2 = args[2].(int32)
		}
		var arg3 int32
		if args[3] != nil {
			arg3 = args[3].(int32)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockTransferRepo_CreateTransfer_Call) Return(err error) *MockTransferRepo_CreateTransfer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTransferRepo_CreateTransfer_Call) RunAndReturn(run func(ctx context.Context, fromUserId int32, toUserId int32, amount int32) error) *MockTransferRepo_CreateTransfer_Call {
	_c.Call.Return(run)
	return _c
}
