// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/tynou/avito-assignment/internal/domain"
)

// NewMockPurchaseRepo creates a new instance of MockPurchaseRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPurchaseRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPurchaseRepo {
	mock := &MockPurchaseRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPurchaseRepo is an autogenerated mock type for the PurchaseRepo type
type MockPurchaseRepo struct {
	mock.Mock
}

type MockPurchaseRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPurchaseRepo) EXPECT() *MockPurchaseRepo_Expecter {
	return &MockPurchaseRepo_Expecter{mock: &_m.Mock}
}

// GetUserInventory provides a mock function for the type MockPurchaseRepo
func (_mock *MockPurchaseRepo) GetUserInventory(ctx context.Context, userId int32) ([]domain.InventoryItem, error) {
	ret := _mock.Called(ctx, userId)

	if len(ret) == 0 {
		panic("no return value specified for GetUserInventory")
	}

	var r0 []domain.InventoryItem
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) ([]domain.InventoryItem, error)); ok {
		return returnFunc(ctx, userId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) []domain.InventoryItem); ok {
		r0 = returnFunc(ctx, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.InventoryItem)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = returnFunc(ctx, userId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPurchaseRepo_GetUserInventory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserInventory'
type MockPurchaseRepo_GetUserInventory_Call struct {
	*mock.Call
}

// GetUserInventory is a helper method to define mock.On call
//   - ctx context.Context
//   - userId int32
func (_e *MockPurchaseRepo_Expecter) GetUserInventory(ctx any, userId any) *MockPurchaseRepo_GetUserInventory_Call {
	return &MockPurchaseRepo_GetUserInventory_Call{Call: _e.mock.On("GetUserInventory", ctx, userId)}
}

func (_c *MockPurchaseRepo_GetUserInventory_Call) Run(run func(ctx context.Context, userId int32)) *MockPurchaseRepo_GetUserInventory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int32
		if args[1] != nil {
			arg1 = args[1].(int32)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPurchaseRepo_GetUserInventory_Call) Return(inventoryItems []domain.InventoryItem, err error) *MockPurchaseRepo_GetUserInventory_Call {
	_c.Call.Return(inventoryItems, err)
	return _c
}

func (_c *MockPurchaseRepo_GetUserInventory_Call) RunAndReturn(run func(ctx context.Context, userId int32) ([]domain.InventoryItem, error)) *MockPurchaseRepo_GetUserInventory_Call {
	_c.Call.Return(run)
	return _c
}
