// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/tynou/avito-assignment/internal/domain"
)

// NewMockTransferRepo creates a new instance of MockTransferRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransferRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransferRepo {
	mock := &MockTransferRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTransferRepo is an autogenerated mock type for the TransferRepo type
type MockTransferRepo struct {
	mock.Mock
}

type MockTransferRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransferRepo) EXPECT() *MockTransferRepo_Expecter {
	return &MockTransferRepo_Expecter{mock: &_m.Mock}
}

// GetReceivedTransfers provides a mock function for the type MockTransferRepo
func (_mock *MockTransferRepo) GetReceivedTransfers(ctx context.Context, userId int32) ([]domain.ReceivedTransfer, error) {
	ret := _mock.Called(ctx, userId)

	if len(ret) == 0 {
		panic("no return value specified for GetReceivedTransfers")
	}

	var r0 []domain.ReceivedTransfer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) ([]domain.ReceivedTransfer, error)); ok {
		return returnFunc(ctx, userId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) []domain.ReceivedTransfer); ok {
		r0 = returnFunc(ctx, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ReceivedTransfer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = returnFunc(ctx, userId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransferRepo_GetReceivedTransfers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReceivedTransfers'
type MockTransferRepo_GetReceivedTransfers_Call struct {
	*mock.Call
}

// GetReceivedTransfers is a helper method to define mock.On call
//   - ctx context.Context
//   - userId int32
func (_e *MockTransferRepo_Expecter) GetReceivedTransfers(ctx any, userId any) *MockTransferRepo_GetReceivedTransfers_Call {
	return &MockTransferRepo_GetReceivedTransfers_Call{Call: _e.mock.On("GetReceivedTransfers", ctx, userId)}
}

func (_c *MockTransferRepo_GetReceivedTransfers_Call) Run(run func(ctx context.Context, userId int32)) *MockTransferRepo_GetReceivedTransfers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int32
		if args[1] != nil {
			arg1 = args[1].(int32)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTransferRepo_GetReceivedTransfers_Call) Return(receivedTransfers []domain.ReceivedTransfer, err error) *MockTransferRepo_GetReceivedTransfers_Call {
	_c.Call.Return(receivedTransfers, err)
	return _c
}

func (_c *MockTransferRepo_GetReceivedTransfers_Call) RunAndReturn(run func(ctx context.Context, userId int32) ([]domain.ReceivedTransfer, error)) *MockTransferRepo_GetReceivedTransfers_Call {
	_c.Call.Return(run)
	return _c
}

// GetSentTransfers provides a mock function for the type MockTransferRepo
func (_mock *MockTransferRepo) GetSentTransfers(ctx context.Context, userId int32) ([]domain.SentTransfer, error) {
	ret := _mock.Called(ctx, userId)

	if len(ret) == 0 {
		panic("no return value specified for GetSentTransfers")
	}

	var r0 []domain.SentTransfer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) ([]domain.SentTransfer, error)); ok {
		return returnFunc(ctx, userId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) []domain.SentTransfer); ok {
		r0 = returnFunc(ctx, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.SentTransfer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = returnFunc(ctx, userId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransferRepo_GetSentTransfers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSentTransfers'
type MockTransferRepo_GetSentTransfers_Call struct {
	*mock.Call
}

// GetSentTransfers is a helper method to define mock.On call
//   - ctx context.Context
//   - userId int32
func (_e *MockTransferRepo_Expecter) GetSentTransfers(ctx any, userId any) *MockTransferRepo_GetSentTransfers_Call {
	return &MockTransferRepo_GetSentTransfers_Call{Call: _e.mock.On("GetSentTransfers", ctx, userId)}
}

func (_c *MockTransferRepo_GetSentTransfers_Call) Run(run func(ctx context.Context, userId int32)) *MockTransferRepo_GetSentTransfers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int32
		if args[1] != nil {
			arg1 = args[1].(int32)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTransferRepo_GetSentTransfers_Call) Return(sentTransfers []domain.SentTransfer, err error) *MockTransferRepo_GetSentTransfers_Call {
	_c.Call.Return(sentTransfers, err)
	return _c
}

func (_c *MockTransferRepo_GetSentTransfers_Call) RunAndReturn(run func(ctx context.Context, userId int32) ([]domain.SentTransfer, error)) *MockTransferRepo_GetSentTransfers_Call {
	_c.Call.Return(run)
	return _c
}
