// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockUserRepo creates a new instance of MockUserRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepo {
	mock := &MockUserRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserRepo is an autogenerated mock type for the UserRepo type
type MockUserRepo struct {
	mock.Mock
}

type MockUserRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepo) EXPECT() *MockUserRepo_Expecter {
	return &MockUserRepo_Expecter{mock: &_m.Mock}
}

// GetUserBalance provides a mock function for the type MockUserRepo
func (_mock *MockUserRepo) GetUserBalance(ctx context.Context, userId int32) (int32, error) {
	ret := _mock.Called(ctx, userId)

	if len(ret) == 0 {
		panic("no return value specified for GetUserBalance")
	}

	var r0 int32
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) (int32, error)); ok {
		return returnFunc(ctx, userId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) int32); ok {
		r0 = returnFunc(ctx, userId)
	} else {
		r0 = ret.Get(0).(int32)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = returnFunc(ctx, userId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepo_GetUserBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserBalance'
type MockUserRepo_GetUserBalance_Call struct {
	*mock.Call
}

// GetUserBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - userId int32
func (_e *MockUserRepo_Expecter) GetUserBalance(ctx any, userId any) *MockUserRepo_GetUserBalance_Call {
	return &MockUserRepo_GetUserBalance_Call{Call: _e.mock.On("GetUserBalance", ctx, userId)}
}

func (_c *MockUserRepo_GetUserBalance_Call) Run(run func(ctx context.Context, userId int32)) *MockUserRepo_GetUserBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int32
		if args[1] != nil {
			arg1 = args[1].(int32)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepo_GetUserBalance_Call) Return(n int32, err error) *MockUserRepo_GetUserBalance_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockUserRepo_GetUserBalance_Call) RunAndReturn(run func(ctx context.Context, userId int32) (int32, error)) *MockUserRepo_GetUserBalance_Call {
	_c.Call.Return(run)
	return _c
}
