// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/tynou/avito-assignment/internal/db"
)

// NewMockQuerier creates a new instance of MockQuerier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQuerier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQuerier {
	mock := &MockQuerier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockQuerier is an autogenerated mock type for the Querier type
type MockQuerier struct {
	mock.Mock
}

type MockQuerier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQuerier) EXPECT() *MockQuerier_Expecter {
	return &MockQuerier_Expecter{mock: &_m.Mock}
}

// CreatePurchase provides a mock function for the type MockQuerier
func (_mock *MockQuerier) CreatePurchase(ctx context.Context, arg db.CreatePurchaseParams) error {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreatePurchase")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.CreatePurchaseParams) error); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQuerier_CreatePurchase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePurchase'
type MockQuerier_CreatePurchase_Call struct {
	*mock.Call
}

// CreatePurchase is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.CreatePurchaseParams
func (_e *MockQuerier_Expecter) CreatePurchase(ctx any, arg any) *MockQuerier_CreatePurchase_Call {
	return &MockQuerier_CreatePurchase_Call{Call: _e.mock.On("CreatePurchase", ctx, arg)}
}

func (_c *MockQuerier_CreatePurchase_Call) Run(run func(ctx context.Context, arg db.CreatePurchaseParams)) *MockQuerier_CreatePurchase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.CreatePurchaseParams
		if args[1] != nil {
			arg1 = args[1].(db.CreatePurchaseParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_CreatePurchase_Call) Return(err error) *MockQuerier_CreatePurchase_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQuerier_CreatePurchase_Call) RunAndReturn(run func(ctx context.Context, arg db.CreatePurchaseParams) error) *MockQuerier_CreatePurchase_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTransfer provides a mock function for the type MockQuerier
func (_mock *MockQuerier) CreateTransfer(ctx context.Context, arg db.CreateTransferParams) error {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateTransfer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.CreateTransferParams) error); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQuerier_CreateTransfer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTransfer'
type MockQuerier_CreateTransfer_Call struct {
	*mock.Call
}

// CreateTransfer is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.CreateTransferParams
func (_e *MockQuerier_Expecter) CreateTransfer(ctx any, arg any) *MockQuerier_CreateTransfer_Call {
	return &MockQuerier_CreateTransfer_Call{Call: _e.mock.On("CreateTransfer", ctx, arg)}
}

func (_c *MockQuerier_CreateTransfer_Call) Run(run func(ctx context.Context, arg db.CreateTransferParams)) *MockQuerier_CreateTransfer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.CreateTransferParams
		if args[1] != nil {
			arg1 = args[1].(db.CreateTransferParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_CreateTransfer_Call) Return(err error) *MockQuerier_CreateTransfer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQuerier_CreateTransfer_Call) RunAndReturn(run func(ctx context.Context, arg db.CreateTransferParams) error) *MockQuerier_CreateTransfer_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function for the type MockQuerier
func (_mock *MockQuerier) CreateUser(ctx context.Context, arg db.CreateUserParams) (int32, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 int32
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.CreateUserParams) (int32, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.CreateUserParams) int32); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Get(0).(int32)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, db.CreateUserParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockQuerier_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.CreateUserParams
func (_e *MockQuerier_Expecter) CreateUser(ctx any, arg any) *MockQuerier_CreateUser_Call {
	return &MockQuerier_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, arg)}
}

func (_c *MockQuerier_CreateUser_Call) Run(run func(ctx context.Context, arg db.CreateUserParams)) *MockQuerier_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.CreateUserParams
		if args[1] != nil {
			arg1 = args[1].(db.CreateUserParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_CreateUser_Call) Return(n int32, err error) *MockQuerier_CreateUser_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockQuerier_CreateUser_Call) RunAndReturn(run func(ctx context.Context, arg db.CreateUserParams) (int32, error)) *MockQuerier_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetMerchByName provides a mock function for the type MockQuerier
func (_mock *MockQuerier) GetMerchByName(ctx context.Context, name string) (db.Merch, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetMerchByName")
	}

	var r0 db.Merch
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (db.Merch, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) db.Merch); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Get(0).(db.Merch)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_GetMerchByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMerchByName'
type MockQuerier_GetMerchByName_Call struct {
	*mock.Call
}

// GetMerchByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockQuerier_Expecter) GetMerchByName(ctx any, name any) *MockQuerier_GetMerchByName_Call {
	return &MockQuerier_GetMerchByName_Call{Call: _e.mock.On("GetMerchByName", ctx, name)}
}

func (_c *MockQuerier_GetMerchByName_Call) Run(run func(ctx context.Context, name string)) *MockQuerier_GetMerchByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_GetMerchByName_Call) Return(merch db.Merch, err error) *MockQuerier_GetMerchByName_Call {
	_c.Call.Return(merch, err)
	return _c
}

func (_c *MockQuerier_GetMerchByName_Call) RunAndReturn(run func(ctx context.Context, name string) (db.Merch, error)) *MockQuerier_GetMerchByName_Call {
	_c.Call.Return(run)
	return _c
}

// GetReceivedTransfers provides a mock function for the type MockQuerier
func (_mock *MockQuerier) GetReceivedTransfers(ctx context.Context, toID int32) ([]db.GetReceivedTransfersRow, error) {
	ret := _mock.Called(ctx, toID)

	if len(ret) == 0 {
		panic("no return value specified for GetReceivedTransfers")
	}

	var r0 []db.GetReceivedTransfersRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) ([]db.GetReceivedTransfersRow, error)); ok {
		return returnFunc(ctx, toID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) []db.GetReceivedTransfersRow); ok {
		r0 = returnFunc(ctx, toID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.GetReceivedTransfersRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = returnFunc(ctx, toID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_GetReceivedTransfers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReceivedTransfers'
type MockQuerier_GetReceivedTransfers_Call struct {
	*mock.Call
}

// GetReceivedTransfers is a helper method to define mock.On call
//   - ctx context.Context
//   - toID int32
func (_e *MockQuerier_Expecter) GetReceivedTransfers(ctx any, toID any) *MockQuerier_GetReceivedTransfers_Call {
	return &MockQuerier_GetReceivedTransfers_Call{Call: _e.mock.On("GetReceivedTransfers", ctx, toID)}
}

func (_c *MockQuerier_GetReceivedTransfers_Call) Run(run func(ctx context.Context, toID int32)) *MockQuerier_GetReceivedTransfers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int32
		if args[1] != nil {
			arg1 = args[1].(int32)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_GetReceivedTransfers_Call) Return(getReceivedTransfersRows []db.GetReceivedTransfersRow, err error) *MockQuerier_GetReceivedTransfers_Call {
	_c.Call.Return(getReceivedTransfersRows, err)
	return _c
}

func (_c *MockQuerier_GetReceivedTransfers_Call) RunAndReturn(run func(ctx context.Context, toID int32) ([]db.GetReceivedTransfersRow, error)) *MockQuerier_GetReceivedTransfers_Call {
	_c.Call.Return(run)
	return _c
}

// GetSentTransfers provides a mock function for the type MockQuerier
func (_mock *MockQuerier) GetSentTransfers(ctx context.Context, fromID int32) ([]db.GetSentTransfersRow, error) {
	ret := _mock.Called(ctx, fromID)

	if len(ret) == 0 {
		panic("no return value specified for GetSentTransfers")
	}

	var r0 []db.GetSentTransfersRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) ([]db.GetSentTransfersRow, error)); ok {
		return returnFunc(ctx, fromID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) []db.GetSentTransfersRow); ok {
		r0 = returnFunc(ctx, fromID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.GetSentTransfersRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = returnFunc(ctx, fromID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_GetSentTransfers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSentTransfers'
type MockQuerier_GetSentTransfers_Call struct {
	*mock.Call
}

// GetSentTransfers is a helper method to define mock.On call
//   - ctx context.Context
//   - fromID int32
func (_e *MockQuerier_Expecter) GetSentTransfers(ctx any, fromID any) *MockQuerier_GetSentTransfers_Call {
	return &MockQuerier_GetSentTransfers_Call{Call: _e.mock.On("GetSentTransfers", ctx, fromID)}
}

func (_c *MockQuerier_GetSentTransfers_Call) Run(run func(ctx context.Context, fromID int32)) *MockQuerier_GetSentTransfers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int32
		if args[1] != nil {
			arg1 = args[1].(int32)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_GetSentTransfers_Call) Return(getSentTransfersRows []db.GetSentTransfersRow, err error) *MockQuerier_GetSentTransfers_Call {
	_c.Call.Return(getSentTransfersRows, err)
	return _c
}

func (_c *MockQuerier_GetSentTransfers_Call) RunAndReturn(run func(ctx context.Context, fromID int32) ([]db.GetSentTransfersRow, error)) *MockQuerier_GetSentTransfers_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserBalance provides a mock function for the type MockQuerier
func (_mock *MockQuerier) GetUserBalance(ctx context.Context, id int32) (int32, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserBalance")
	}

	var r0 int32
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) (int32, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) int32); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(int32)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_GetUserBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserBalance'
type MockQuerier_GetUserBalance_Call struct {
	*mock.Call
}

// GetUserBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *MockQuerier_Expecter) GetUserBalance(ctx any, id any) *MockQuerier_GetUserBalance_Call {
	return &MockQuerier_GetUserBalance_Call{Call: _e.mock.On("GetUserBalance", ctx, id)}
}

func (_c *MockQuerier_GetUserBalance_Call) Run(run func(ctx context.Context, id int32)) *MockQuerier_GetUserBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int32
		if args[1] != nil {
			arg1 = args[1].(int32)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_GetUserBalance_Call) Return(n int32, err error) *MockQuerier_GetUserBalance_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockQuerier_GetUserBalance_Call) RunAndReturn(run func(ctx context.Context, id int32) (int32, error)) *MockQuerier_GetUserBalance_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByUsername provides a mock function for the type MockQuerier
func (_mock *MockQuerier) GetUserByUsername(ctx context.Context, username string) (db.User, error) {
	ret := _mock.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByUsername")
	}

	var r0 db.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (db.User, error)); ok {
		return returnFunc(ctx, username)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) db.User); ok {
		r0 = returnFunc(ctx, username)
	} else {
		r0 = ret.Get(0).(db.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, username)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_GetUserByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByUsername'
type MockQuerier_GetUserByUsername_Call struct {
	*mock.Call
}

// GetUserByUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *MockQuerier_Expecter) GetUserByUsername(ctx any, username any) *MockQuerier_GetUserByUsername_Call {
	return &MockQuerier_GetUserByUsername_Call{Call: _e.mock.On("GetUserByUsername", ctx, username)}
}

func (_c *MockQuerier_GetUserByUsername_Call) Run(run func(ctx context.Context, username string)) *MockQuerier_GetUserByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_GetUserByUsername_Call) Return(user db.User, err error) *MockQuerier_GetUserByUsername_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockQuerier_GetUserByUsername_Call) RunAndReturn(run func(ctx context.Context, username string) (db.User, error)) *MockQuerier_GetUserByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserForUpdate provides a mock function for the type MockQuerier
func (_mock *MockQuerier) GetUserForUpdate(ctx context.Context, id int32) (db.GetUserForUpdateRow, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserForUpdate")
	}

	var r0 db.GetUserForUpdateRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) (db.GetUserForUpdateRow, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) db.GetUserForUpdateRow); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(db.GetUserForUpdateRow)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_GetUserForUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserForUpdate'
type MockQuerier_GetUserForUpdate_Call struct {
	*mock.Call
}

// GetUserForUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *MockQuerier_Expecter) GetUserForUpdate(ctx any, id any) *MockQuerier_GetUserForUpdate_Call {
	return &MockQuerier_GetUserForUpdate_Call{Call: _e.mock.On("GetUserForUpdate", ctx, id)}
}

func (_c *MockQuerier_GetUserForUpdate_Call) Run(run func(ctx context.Context, id int32)) *MockQuerier_GetUserForUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int32
		if args[1] != nil {
			arg1 = args[1].(int32)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_GetUserForUpdate_Call) Return(getUserForUpdateRow db.GetUserForUpdateRow, err error) *MockQuerier_GetUserForUpdate_Call {
	_c.Call.Return(getUserForUpdateRow, err)
	return _c
}

func (_c *MockQuerier_GetUserForUpdate_Call) RunAndReturn(run func(ctx context.Context, id int32) (db.GetUserForUpdateRow, error)) *MockQuerier_GetUserForUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserInventory provides a mock function for the type MockQuerier
func (_mock *MockQuerier) GetUserInventory(ctx context.Context, userID int32) ([]db.GetUserInventoryRow, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserInventory")
	}

	var r0 []db.GetUserInventoryRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) ([]db.GetUserInventoryRow, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) []db.GetUserInventoryRow); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.GetUserInventoryRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQuerier_GetUserInventory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserInventory'
type MockQuerier_GetUserInventory_Call struct {
	*mock.Call
}

// GetUserInventory is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int32
func (_e *MockQuerier_Expecter) GetUserInventory(ctx any, userID any) *MockQuerier_GetUserInventory_Call {
	return &MockQuerier_GetUserInventory_Call{Call: _e.mock.On("GetUserInventory", ctx, userID)}
}

func (_c *MockQuerier_GetUserInventory_Call) Run(run func(ctx context.Context, userID int32)) *MockQuerier_GetUserInventory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int32
		if args[1] != nil {
			arg1 = args[1].(int32)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_GetUserInventory_Call) Return(getUserInventoryRows []db.GetUserInventoryRow, err error) *MockQuerier_GetUserInventory_Call {
	_c.Call.Return(getUserInventoryRows, err)
	return _c
}

func (_c *MockQuerier_GetUserInventory_Call) RunAndReturn(run func(ctx context.Context, userID int32) ([]db.GetUserInventoryRow, error)) *MockQuerier_GetUserInventory_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUserBalance provides a mock function for the type MockQuerier
func (_mock *MockQuerier) UpdateUserBalance(ctx context.Context, arg db.UpdateUserBalanceParams) error {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserBalance")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, db.UpdateUserBalanceParams) error); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQuerier_UpdateUserBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserBalance'
type MockQuerier_UpdateUserBalance_Call struct {
	*mock.Call
}

// UpdateUserBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.UpdateUserBalanceParams
func (_e *MockQuerier_Expecter) UpdateUserBalance(ctx any, arg any) *MockQuerier_UpdateUserBalance_Call {
	return &MockQuerier_UpdateUserBalance_Call{Call: _e.mock.On("UpdateUserBalance", ctx, arg)}
}

func (_c *MockQuerier_UpdateUserBalance_Call) Run(run func(ctx context.Context, arg db.UpdateUserBalanceParams)) *MockQuerier_UpdateUserBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 db.UpdateUserBalanceParams
		if args[1] != nil {
			arg1 = args[1].(db.UpdateUserBalanceParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQuerier_UpdateUserBalance_Call) Return(err error) *MockQuerier_UpdateUserBalance_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQuerier_UpdateUserBalance_Call) RunAndReturn(run func(ctx context.Context, arg db.UpdateUserBalanceParams) error) *MockQuerier_UpdateUserBalance_Call {
	_c.Call.Return(run)
	return _c
}
