// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/tynou/avito-assignment/internal/db"
)

// NewMockPurchaseRepo creates a new instance of MockPurchaseRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPurchaseRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPurchaseRepo {
	mock := &MockPurchaseRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPurchaseRepo is an autogenerated mock type for the PurchaseRepo type
type MockPurchaseRepo struct {
	mock.Mock
}

type MockPurchaseRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPurchaseRepo) EXPECT() *MockPurchaseRepo_Expecter {
	return &MockPurchaseRepo_Expecter{mock: &_m.Mock}
}

// CreatePurchase provides a mock function for the type MockPurchaseRepo
func (_mock *MockPurchaseRepo) CreatePurchase(ctx context.Context, userId int32, merch db.Merch) error {
	ret := _mock.Called(ctx, userId, merch)

	if len(ret) == 0 {
		panic("no return value specified for CreatePurchase")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32, db.Merch) error); ok {
		r0 = returnFunc(ctx, userId, merch)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPurchaseRepo_CreatePurchase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePurchase'
type MockPurchaseRepo_CreatePurchase_Call struct {
	*mock.Call
}

// CreatePurchase is a helper method to define mock.On call
//   - ctx context.Context
//   - userId int32
//   - merch db.Merch
func (_e *MockPurchaseRepo_Expecter) CreatePurchase(ctx any, userId any, merch any) *MockPurchaseRepo_CreatePurchase_Call {
	return &MockPurchaseRepo_CreatePurchase_Call{Call: _e.mock.On("CreatePurchase", ctx, userId, merch)}
}

func (_c *MockPurchaseRepo_CreatePurchase_Call) Run(run func(ctx context.Context, userId int32, merch db.Merch)) *MockPurchaseRepo_CreatePurchase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int32
		if args[1] != nil {
			arg1 = args[1].(int32)
		}
		var arg2 db.Merch
		if args[2] != nil {
			arg2 = args[2].(db.Merch)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPurchaseRepo_CreatePurchase_Call) Return(err error) *MockPurchaseRepo_CreatePurchase_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPurchaseRepo_CreatePurchase_Call) RunAndReturn(run func(ctx context.Context, userId int32, merch db.Merch) error) *MockPurchaseRepo_CreatePurchase_Call {
	_c.Call.Return(run)
	return _c
}
