// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/tynou/avito-assignment/internal/db"
)

// NewMockMerchRepo creates a new instance of MockMerchRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMerchRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMerchRepo {
	mock := &MockMerchRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMerchRepo is an autogenerated mock type for the MerchRepo type
type MockMerchRepo struct {
	mock.Mock
}

type MockMerchRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMerchRepo) EXPECT() *MockMerchRepo_Expecter {
	return &MockMerchRepo_Expecter{mock: &_m.Mock}
}

// GetMerchByName provides a mock function for the type MockMerchRepo
func (_mock *MockMerchRepo) GetMerchByName(ctx context.Context, name string) (db.Merch, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetMerchByName")
	}

	var r0 db.Merch
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (db.Merch, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) db.Merch); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Get(0).(db.Merch)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMerchRepo_GetMerchByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMerchByName'
type MockMerchRepo_GetMerchByName_Call struct {
	*mock.Call
}

// GetMerchByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockMerchRepo_Expecter) GetMerchByName(ctx any, name any) *MockMerchRepo_GetMerchByName_Call {
	return &MockMerchRepo_GetMerchByName_Call{Call: _e.mock.On("GetMerchByName", ctx, name)}
}

func (_c *MockMerchRepo_GetMerchByName_Call) Run(run func(ctx context.Context, name string)) *MockMerchRepo_GetMerchByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMerchRepo_GetMerchByName_Call) Return(merch db.Merch, err error) *MockMerchRepo_GetMerchByName_Call {
	_c.Call.Return(merch, err)
	return _c
}

func (_c *MockMerchRepo_GetMerchByName_Call) RunAndReturn(run func(ctx context.Context, name string) (db.Merch, error)) *MockMerchRepo_GetMerchByName_Call {
	_c.Call.Return(run)
	return _c
}
