// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

type CoinTransfer struct {
	ID     int32
	FromID int32
	ToID   int32
	Amount int32
}

type Merch struct {
	ID    int32
	Name  string
	Price int32
}

type Purchase struct {
	ID      int32
	UserID  int32
	MerchID int32
}

type User struct {
	ID           int32
	Username     string
	PasswordHash string
	Balance      int32
}
