// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CreatePurchase(ctx context.Context, arg CreatePurchaseParams) error
	CreateTransfer(ctx context.Context, arg CreateTransferParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (int32, error)
	GetMerchByName(ctx context.Context, name string) (Merch, error)
	GetReceivedTransfers(ctx context.Context, toID int32) ([]GetReceivedTransfersRow, error)
	GetSentTransfers(ctx context.Context, fromID int32) ([]GetSentTransfersRow, error)
	GetUserBalance(ctx context.Context, id int32) (int32, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUserForUpdate(ctx context.Context, id int32) (GetUserForUpdateRow, error)
	GetUserInventory(ctx context.Context, userID int32) ([]GetUserInventoryRow, error)
	UpdateUserBalance(ctx context.Context, arg UpdateUserBalanceParams) error
}

var _ Querier = (*Queries)(nil)
